### ISSUE TITLE
Problemas ao aplicar o plugin `metrics-plugin` quando o projeto foi definido para utilizar Maven como ferramenta de build

### ISSUE THREAD

**Issue by dearrudam** [stack-spot/graphene-java-api-stack#7]
Problemas ao aplicar o plugin metrics-plugin quando o projeto foi definido para utilizar Maven como ferramenta de build.

Segue o output como evidência do problema:

```bash
workspace/ $ stk create app meu-teste-app --stackfile graphene-java-api-stack/default 
? Select the Spring Boot version 3.0.0-M4
? Inform the project artifact ID meu-teste-app
? Enter a version for the project  (0.0.1-SNAPSHOT)
? Enter a Group ID for the project  (br.com.graphene)
? Select the Java version 17
? Select the project build tool Maven
- Application meu-teste-app successfully created!
workspace/ $ cd meu-teste-app/
meu-teste-app/ (main) $ stk apply plugin 
metrics-plugin  tracing-plugin  
meu-teste-app/ (main) $ stk apply plugin metrics-plugin 

ERROR: > File in path /home/maximillianarruda/workspace/meu-teste-app/build.gradle was not found.
meu-teste-app/ (main) $ cat ~/.stk/logs/logs.log 

ERROR - 2022-09-13 12:59:17,991

> File in path /home/maximillianarruda/workspace/meu-teste-app/build.gradle was not found.
Traceback (most recent call last):
  File "templateframework/utils/file.py", line 71, in handle_read_file
FileNotFoundError: [Errno 2] No such file or directory: '/home/maximillianarruda/workspace/meu-teste-app/build.gradle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 97, in main
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1626, in _process_result
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 26, in new_func
  File "cli.py", line 90, in process_result
  File "metrics/send.py", line 30, in decorator
  File "plugin/apply.py", line 120, in apply_plugin
  File "templateframework/runner.py", line 61, in apply_template
  File "templateframework/template.py", line 87, in run
  File "templateframework/template.py", line 140, in apply
  File "templateframework/hooks/__init__.py", line 67, in run_after_render_hooks
  File "templateframework/hooks/__init__.py", line 53, in __run_trigger_hooks
  File "templateframework/hooks/edit_text.py", line 155, in edit_hook
  File "templateframework/utils/file.py", line 74, in handle_read_file
templateframework.exception.business_exception.BusinessException: > File in path /home/maximillianarruda/workspace/meu-teste-app/build.gradle was not found.

```

O problema ocorre pois os plugins `metrics-plugin` não está preparado para ser aplicado em projetos que não estão utilizando Gradle como ferramenta de build. Como o projeto foi criado utilizando Maven como ferramenta de build, sempre que aplicarmos esses plugins, o problema irá ocorrer.

**Comment by lucas-almeida-zup** [comment]
@dearrudam obrigado pela identificação do problema, mapeamos a correção no PR: [fix/metrics-plugin](https://github.com/stack-spot/graphene-java-api-stack/pull/11)
